### ISSUE TITLE
BUG(SDK): Loading 'release' build into Sanity fails

### ISSUE THREAD

**Issue by Cosmin-Parvulescu** [kubelt/kubelt#264]
## I'm submitting a ...

- [x] bug report

## What is the current behavior?

Currently, when trying to run the sanity studio with the plugin loading a 'release' version of the SDK, it fails when loading Sanity Studio.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Run either :build or :watch on ```sanity-plugin-kubelt```;
2. Add plugin to local sanity studio instance;
3. Run local sanity studio instance (```sanity start```);
4. See error.

```
TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.4289 (/static/js/app.bundle.js:403509:377804)
    at t (/static/js/app.bundle.js:403509:634826)
    at Object.5909 (/static/js/app.bundle.js:403509:381455)
    at t (/static/js/app.bundle.js:403509:634826)
    at Object.956 (/static/js/app.bundle.js:403509:361747)
    at t (/static/js/app.bundle.js:403509:634826)
    at Object.5581 (/static/js/app.bundle.js:403509:361922)
    at t (/static/js/app.bundle.js:403509:634826)
    at Object.4560 (/static/js/app.bundle.js:403509:425107)
    at t (/static/js/app.bundle.js:403509:634826)
```

## What is the expected behavior?

Don't see error.

## What is the motivation / use case for changing the behavior?

The release version should make sure that no important piece of code gets removed when building for web.

## Please tell us about your environment:

Version: 
Browser or OS: Brave / Edge

**Comment by Cosmin-Parvulescu** [comment]
Closing this is not rly a bug. According to discussions the resolution is to use the development build for plugin concerns as that gets webpackd.
