### ISSUE TITLE
BUG(SDK): Authentication endpoint fails to complete

### ISSUE THREAD

**Issue by Cosmin-Parvulescu** [kubelt/kubelt#265]
## I'm submitting a ...

- [x] bug report

## What is the current behavior?

**In a Sanity Studio context!**

When calling the SDK core authenticate endpoint, it returns an error in the console, while also producing a workable SDK result. This is not correct behavior both in the sense that an exception should not return, perhaps, and that it would be nice to be able to e2e authenticate.

## If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Initialize SDK;
```
import kSdkWeb from "@kubelt/sdk-web";

const initSDK = await kSdkWeb?.node_v1?.init();
```
2. Register wallet to SDK;
```
const wallet: IKubeltSdkWallet = {
  address: account, // current wallet address
  signFn: signFn, // async (signable: string) => string
};

const walletInitSDK = await kSdkWeb?.node_v1?.core.setWallet(
  initSDK,
  wallet
);
```
3. Authenticate against personal core;
```
const authedSdk = await kSdkWeb.node_v1.core.authenticate(
  walletInitSDK,
  account
);
```
4. Observe error and cleared SDK object returned.
```
// Error
ErrorHandler.js:50 TypeError: c.cljs$core$async$impl$protocols$ReadPort$take_BANG_$arity$2 is not a function
    at Object.cljs$core$async$impl$ioc_helpers$take_BANG_ [as take_BANG_] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at switch__20777__auto__ (com.kubelt.sdk.v1.core.js:39:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at Function.com$kubelt$sdk$v1$core$authenticate_BANG__$_state_machine__20778__auto____1 [as cljs$core$IFn$_invoke$arity$1] (com.kubelt.sdk.v1.core.js:39:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine [as run_state_machine] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped [as run_state_machine_wrapped] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at cljs$core$async$impl$dispatch$process_messages (cljs.core.async.impl.dispatch.js:1:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)
(anonymous) @ ErrorHandler.js:50
error (async)
(anonymous) @ ErrorHandler.js:65
commitHookEffectListMount @ react-dom.development.js:19732
commitPassiveHookEffects @ react-dom.development.js:19770
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
flushPassiveEffectsImpl @ react-dom.development.js:22854
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
flushPassiveEffects @ react-dom.development.js:22821
performSyncWorkOnRoot @ react-dom.development.js:21738
(anonymous) @ react-dom.development.js:11090
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
flushSyncCallbackQueueImpl @ react-dom.development.js:11085
flushSyncCallbackQueue @ react-dom.development.js:11073
unbatchedUpdates @ react-dom.development.js:21910
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24758
render @ react-dom.development.js:24841
render @ entry-dev.js:17
(anonymous) @ entry-dev.js:20
__webpack_require__ @ bootstrap 3beb796e780d64e11685:712
fn @ bootstrap 3beb796e780d64e11685:117
(anonymous) @ react-hot-loader.production.min.js:1
__webpack_require__ @ bootstrap 3beb796e780d64e11685:712
webpackJsonpCallback @ bootstrap 3beb796e780d64e11685:25
(anonymous) @ app.bundle.js:1
cljs.core.async.impl.ioc_helpers.js:105 Uncaught TypeError: c.cljs$core$async$impl$protocols$ReadPort$take_BANG_$arity$2 is not a function
    at Object.cljs$core$async$impl$ioc_helpers$take_BANG_ [as take_BANG_] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at switch__20777__auto__ (com.kubelt.sdk.v1.core.js:39:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at Function.com$kubelt$sdk$v1$core$authenticate_BANG__$_state_machine__20778__auto____1 [as cljs$core$IFn$_invoke$arity$1] (com.kubelt.sdk.v1.core.js:39:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine [as run_state_machine] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped [as run_state_machine_wrapped] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at cljs$core$async$impl$dispatch$process_messages (cljs.core.async.impl.dispatch.js:1:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)
cljs$core$async$impl$ioc_helpers$take_BANG_ @ cljs.core.async.impl.ioc_helpers.js:105
switch__20777__auto__ @ com.kubelt.sdk.v1.core.js:39
(anonymous) @ com.kubelt.sdk.v1.core.js:39
com$kubelt$sdk$v1$core$authenticate_BANG__$_state_machine__20778__auto____1 @ com.kubelt.sdk.v1.core.js:39
cljs$core$async$impl$ioc_helpers$run_state_machine @ cljs.core.async.impl.ioc_helpers.js:105
cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped @ cljs.core.async.impl.ioc_helpers.js:105
(anonymous) @ com.kubelt.sdk.v1.core.js:39
cljs$core$async$impl$dispatch$process_messages @ cljs.core.async.impl.dispatch.js:1
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
goog.async.nextTick @ cljs_env.js:1440
cljs$core$async$impl$dispatch$queue_dispatcher @ cljs.core.async.impl.dispatch.js:1
cljs$core$async$impl$dispatch$run @ cljs.core.async.impl.dispatch.js:1
com$kubelt$sdk$v1$core$authenticate_BANG_ @ com.kubelt.sdk.v1.core.js:39
(anonymous) @ com.kubelt.sdk.v1.core.js:240
com$kubelt$lib$promise$promise @ com.kubelt.lib.promise.js:46
com$kubelt$sdk$v1$core$authenticate_js_BANG_ @ com.kubelt.sdk.v1.core.js:240
(anonymous) @ kubeltWallet.ts:97
asyncGeneratorStep @ kubeltWallet.ts:9
_next @ kubeltWallet.ts:9
(anonymous) @ kubeltWallet.ts:9
(anonymous) @ kubeltWallet.ts:9
requestKubeltAuth @ kubeltWallet.ts:87
(anonymous) @ KubeltAuth.tsx:13
asyncGeneratorStep @ KubeltAuth.tsx:6
_next @ KubeltAuth.tsx:6
(anonymous) @ KubeltAuth.tsx:6
(anonymous) @ KubeltAuth.tsx:6
kubeltLogin @ KubeltAuth.tsx:12
onClick @ KubeltAuth.tsx:39
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:307
executeDispatch @ react-dom.development.js:390
executeDispatchesInOrder @ react-dom.development.js:415
executeDispatchesAndRelease @ react-dom.development.js:3279
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3288
forEachAccumulated @ react-dom.development.js:3260
runEventsInBatch @ react-dom.development.js:3305
runExtractedPluginEventsInBatch @ react-dom.development.js:3515
handleTopLevel @ react-dom.development.js:3559
batchedEventUpdates$1 @ react-dom.development.js:21872
batchedEventUpdates @ react-dom.development.js:796
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3569
attemptToDispatchEvent @ react-dom.development.js:4268
dispatchEvent @ react-dom.development.js:4190
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
discreteUpdates$1 @ react-dom.development.js:21888
discreteUpdates @ react-dom.development.js:807
dispatchDiscreteEvent @ react-dom.development.js:4169
Show 25 more frames
ErrorHandler.js:50 Error: Assert failed: (string? core)
    at Object.com$kubelt$lib$p2p$authenticate_BANG_ [as authenticate_BANG_] (com.kubelt.lib.p2p.js:34:1)
    at switch__20777__auto__ (com.kubelt.sdk.v1.core.js:39:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at Function.com$kubelt$sdk$v1$core$authenticate_BANG__$_state_machine__20778__auto____1 [as cljs$core$IFn$_invoke$arity$1] (com.kubelt.sdk.v1.core.js:39:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine [as run_state_machine] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped [as run_state_machine_wrapped] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at cljs$core$async$impl$dispatch$process_messages (cljs.core.async.impl.dispatch.js:1:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)
(anonymous) @ ErrorHandler.js:50
error (async)
(anonymous) @ ErrorHandler.js:65
commitHookEffectListMount @ react-dom.development.js:19732
commitPassiveHookEffects @ react-dom.development.js:19770
callCallback @ react-dom.development.js:189
invokeGuardedCallbackDev @ react-dom.development.js:238
invokeGuardedCallback @ react-dom.development.js:293
flushPassiveEffectsImpl @ react-dom.development.js:22854
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
flushPassiveEffects @ react-dom.development.js:22821
performSyncWorkOnRoot @ react-dom.development.js:21738
(anonymous) @ react-dom.development.js:11090
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11040
flushSyncCallbackQueueImpl @ react-dom.development.js:11085
flushSyncCallbackQueue @ react-dom.development.js:11073
unbatchedUpdates @ react-dom.development.js:21910
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24758
render @ react-dom.development.js:24841
render @ entry-dev.js:17
(anonymous) @ entry-dev.js:20
__webpack_require__ @ bootstrap 3beb796e780d64e11685:712
fn @ bootstrap 3beb796e780d64e11685:117
(anonymous) @ react-hot-loader.production.min.js:1
__webpack_require__ @ bootstrap 3beb796e780d64e11685:712
webpackJsonpCallback @ bootstrap 3beb796e780d64e11685:25
(anonymous) @ app.bundle.js:1
com.kubelt.lib.p2p.js:34 Uncaught Error: Assert failed: (string? core)
    at Object.com$kubelt$lib$p2p$authenticate_BANG_ [as authenticate_BANG_] (com.kubelt.lib.p2p.js:34:1)
    at switch__20777__auto__ (com.kubelt.sdk.v1.core.js:39:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at Function.com$kubelt$sdk$v1$core$authenticate_BANG__$_state_machine__20778__auto____1 [as cljs$core$IFn$_invoke$arity$1] (com.kubelt.sdk.v1.core.js:39:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine [as run_state_machine] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at Object.cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped [as run_state_machine_wrapped] (cljs.core.async.impl.ioc_helpers.js:105:1)
    at com.kubelt.sdk.v1.core.js:39:1
    at cljs$core$async$impl$dispatch$process_messages (cljs.core.async.impl.dispatch.js:1:1)
    at run (setImmediate.js:40:1)
    at runIfPresent (setImmediate.js:69:1)

// Cleared SDK
{
    "takes": {
        "head": 0,
        "tail": 0,
        "length": 0,
        "arr": [
            null,
            ...
        ]
    },
    "dirty_takes": 0,
    "puts": {
        "head": 0,
        "tail": 0,
        "length": 0,
        "arr": [
            null,
            ...
        ]
    },
    "dirty_puts": 0,
    "buf": {
        "buf": {
            "head": 0,
            "tail": 0,
            "length": 0,
            "arr": [
                null
            ]
        },
        "n": 1,
        "cljs$lang$protocol_mask$partition0$": 2,
        "cljs$lang$protocol_mask$partition1$": 0
    },
    "closed": true
}
```

## What is the expected behavior?

I would like to authenticate, get an authenticated SDK that can be further used to make additional calls, such as adding resources.

## What is the motivation / use case for changing the behavior?

Not being able to e2e authenticate in the Sanity Studio context will not allow us to offer an easy hop-in for users.

## Please tell us about your environment:

Version:
Browser or OS: Brave / Edge on Windows 10

**Comment by Cosmin-Parvulescu** [comment]
I forgot to mention, this might be of interest, the 1st 'auth' call gets properly sent.

```http://127.0.0.1:8787/@0x6c60da9471181aa54c648c6e201263a5501363f3/auth```
```
{
    "nonce": "0x05c2b92ef96dfe6ab02bdb0917aa9fc6ff43a9ffe4c2b3d9"
}
```
